# Generated by Django 2.2.7 on 2020-04-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_workout_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
    ]
